spring:

#  datasource:
#    username:
#    password:
#    driver-class-name: org.postgresql.Driver
#    url:

  jpa:
    properties:
      hibernate:
        default_schema: public

  liquibase:
    enabled: true
    change-log: db/changelog/master.yaml

  docker:
    compose:
      file: src/main/docker/compose.yaml
      enabled: true
      lifecycle-management: start_only

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
